app/models/models.py
#  will contain all the models required for this project 
#  like user model for login, registration, blog model for blogs etc.


class User:
    pass

# create note schema
class Blog:
      pass

app/__init__.py
# The __init__.py file makes Python treat directories containing it as modules.
# Furthermore, this is the first file to be loaded in a module,
# so you can use it to execute code that you want to run each time a module is loaded, or specify the submodules to be exported.
from flask import Flask, session

def create_app():
    app = Flask(__name__) 

    app.config['SECRET_KEY']  = 'THIS IS THE SUPER SECRET KEY' # makes client site session secure

    # import routes . = current directory
    from .views import views
    from .auth import auth

    # register the blue prints
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/auth") # route starts from /auth/

    return app

app/auth.py
# contains route related to authentication like login 
from flask import  redirect, render_template, Blueprint, request, url_for, session
from app.db_config import get_connection
import datetime

auth = Blueprint('auth', __name__)  # define blue print, auth is just a user friendly name

"""
 Login page for admin
 @get request
"""
@auth.route('/login-page',methods=['get'])
def get_login_page():
      if session['remember_me'] == True and len(session['username']) >5:
            print(' user is already logged in')
            return redirect(url_for('auth.add_blogs'), code=301)
      return render_template("admin_login/login.html", title = "Admin Login")

"""
Actual login form submission
Post request
"""
@auth.route('/login', methods=['post'])  
def login() :
    form_data = request.form
    username, password, remember_me = form_data.get('email'), form_data.get('password'), form_data.get('remember')
  
    if len(username) < 1 or len(password) <1 :
        return render_template("admin_login/login.html",  error_message = "Please enter all the credentials")

    connection, cursor = get_connection()
    try:
        fetch_query = "SELECT * FROM users WHERE username =%s AND password = %s"
        cursor.execute(fetch_query, (username, password)) # expects more than one value in tuple
        data = cursor.fetchall()
        if len(data) > 0:
            # store username in session
            session['username'] = data[0][1] 
            if remember_me == 'on':
                 session['remember_me'] = True
            return redirect(url_for('auth.add_blogs'), code=301) 

        else:
            return render_template("admin_login/login.html", error_message = "Please enter correct credentials")

    except(ConnectionError, Exception) as error:
        return render_template("admin_login/login.html", error_message = "Something went wrong while fetching records from the database : " + str(error))
    finally:
        cursor.close()
        connection.close() 

"""
get request to logout for admin
should redirect to /
"""
@auth.route('/logout', methods=['get', 'post'])
def logout():
    return "Logout Page" # have to redirect after killing session or something like that.   


@auth.route('/add/blogs', methods=['get', 'post'])
def add_blogs():
    if not session['username']:
          return redirect(url_for('auth.get_login_page'), code=301)
    title,home_nav_text, blogs_nav_text, admin_login_nav_text, search_nav_text,brand_nav_text = "Add your new blogs!", "Home", 'Blogs', 'Admin Login', 'Search','Amigos Blogs'
    template_context = dict(title = title, home_nav_text = home_nav_text, blogs_nav_text = blogs_nav_text,admin_login_nav_text=admin_login_nav_text,search_nav_text=search_nav_text,brand_nav_text = brand_nav_text)
     
    if request.method == 'GET':
        # get data from the form     
        return render_template("admin_login/add_blog.html", **template_context) 
    # if post request, validates & adds to the database    
    creator = session['username'] 
    form_data = request.form
    blog_tilte, blog_content, img_url, blog_created_date, blog_created_by = form_data.get('title'), form_data.get('content'), form_data.get('img_url'), datetime.datetime.now(), creator
    if(len(blog_tilte) <10 or len(blog_content) < 20):
        return render_template("admin_login/add_blog.html", error_message = 'Please give proper title & description.') 

    connection, cursor = get_connection()

    insert_into_blogs_query = 'INSERT INTO blogs(title, content, img_url, created_on, creator) values(%s, %s, %s, %s, %s)'

    try:
        cursor.execute(insert_into_blogs_query, ( blog_tilte, blog_content, img_url, blog_created_date, blog_created_by))
        connection.commit()    

    except(ConnectionError) as connection_error:
        print("Something went wrong while inserting into database : ", connection_error)

    finally:
        connection.close()
        cursor.close()

     # get data from the form     
    return render_template("admin_login/add_blog.html", success_message = 'Blog create successfully')

    

app/views.py
#  contains all the routes 
#  define as blue print i.e tell that it contains bunch of routes

from flask import render_template, Blueprint, session,redirect, url_for
import flask
from app.db_config import get_connection

views = Blueprint('views', __name__)  # define blue print, name = views , we can call it routes as well.

"""
 Renders home page with navbar & Image
 renders home.html [from templates dir]
 @get request
"""
@views.route('/')
def index():
     # set default session
     session['remember_me'] = False
     session['username'] = ''

     title,home_nav_text, blogs_nav_text, admin_login_nav_text, search_nav_text,brand_nav_text = "My Blogs - Powered with flask !", "Home", 'Blogs', 'Admin Login', 'Search','Amigos Blogs'
     template_context = dict(title = title, home_nav_text = home_nav_text, blogs_nav_text = blogs_nav_text,admin_login_nav_text=admin_login_nav_text,search_nav_text=search_nav_text,brand_nav_text = brand_nav_text)
     return render_template('home.html', **template_context)

"""
Lists of all blogs in the database
Accessible to all the users
@get request 
"""
@views.route('/blogs', methods = ['get'])
def get_blogs():
     title,home_nav_text, blogs_nav_text, admin_login_nav_text, search_nav_text,brand_nav_text, all_amigos_blogs_text = "My Blogs - Powered with flask !", "Home", 'Blogs', 'Admin Login', 'Search','Amigos Blogs','All Amigos Blogs'
     template_context = dict(title = title, home_nav_text = home_nav_text, blogs_nav_text = blogs_nav_text,admin_login_nav_text=admin_login_nav_text,search_nav_text=search_nav_text,brand_nav_text = brand_nav_text, all_amigos_blogs_text = all_amigos_blogs_text)
     blogs = None
     blogs_dict = None

     connection,cursor  = get_connection() 

     try:
          fetch_blogs_query = "SELECT * FROM blogs"
          cursor.execute(fetch_blogs_query)
          # store the data 
          blogs = cursor.fetchall()
          blogs_dict = {
               'blogs' : blogs
          }
          template_context['blogs'] = blogs_dict
     except(ConnectionError) as connection_error:
        print("Something went wrong while fetching blogs from the database : ", connection_error )
     
     finally:
        cursor.close()
        connection.close()   
        print(template_context , ' template')          
     return render_template('blogs/blogs.html', **template_context)
     

"""
Retrieve specific blog from the d
@Get request
Accessible for all users
"""
@views.route('/blogs/<int:blog_id>')   
def get_blog_by_id(blog_id):
     # grab the ID of blog
     # query against db
     # display the single blog
    return "Blog with ID : {}".format(blog_id )


@views.route("/about")
def about_app():
    about = {
        'app_name' : 'Amigos Blogs',
        'app_version' : '1.0.0',
        'flask_version' : flask.__version__,
        'app_developer' : 'Badri Paudel',
        'developer_github_link' : 'https://github.com/badripaudel77/flask-web-blogs'
    }
    return about

app/templates/admin_login/add_blog.html
<!-- add the blog -->

<!DOCTYPE html>
<html lang="en">
    <head>
    <title>{{title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container" style="margin: 50px;">
        <h2>Add your new blogs</h2>
         {% if error_message %}
             <p style="color: red;">*** {{ error_message }} ***</p>
         {% endif %}
         {% if success_message %}
         <p style="color: green;">{{ success_message }} !</p>
         {% endif %}
         <form method="post" action="/auth/add/blogs" novalidate>
             <div class="mb-3 mt-3">
               <label for="title">Blog Title:</label>
               <input type="text" class="form-control" id="title" placeholder="Enter your title for blog" name="title">
             </div>
             <div class="mb-3 mt-3">
                <label for="img_url">Image URL:</label>
                <input type="text" class="form-control" id="img_url" placeholder="Enter your image url for blog post" name="img_url">
              </div>
             <div class="mb-3">
               <label for="content">Blog Content:</label>
               <textarea rows="10" class="form-control" id="pwd" placeholder="Enter your blog content" name="content"></textarea>
             </div>
             <div>
                 <button type="submit" class="btn btn-primary">Post Blog</button>
                 <a class="btn btn-outline-warning" href="/blogs" style="margin-left: 10px;">Go to blogs page</a>
             </div>
           </form>
     </div>
</body>
</html>

app/templates/admin_login/login.html
<!-- admin login -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{title}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container mt-3">
   <h2>Admin Login Form</h2>
    {% if error_message %}
        <p style="color: red;">*** {{ error_message }} ***</p>
    {% endif %}
    <form method="post" action="login" novalidate>
        <div class="mb-3 mt-3">
          <label for="email">Your Email:</label>
          <input type="email" class="form-control" id="email" placeholder="Enter your valid email" name="email">
        </div>
        <div class="mb-3">
          <label for="pwd">Your Password:</label>
          <input type="password" class="form-control" id="pwd" placeholder="Enter your valid password" name="password">
        </div>
        <div class="form-check mb-3">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" name="remember"> Remember me next time
          </label>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Login to app</button>
            <a class="btn btn-outline-warning" href="/" style="margin-left: 10px;">Go to home page</a>
        </div>
      </form>
</div>
</body>
</html>

app/templates/blogs/blogs.html
<!-- contains the list of blogs from the database -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{all_amigos_blogs_text}}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    </head>
<body>
     <!-- Include navbar here from navbar.html -->
     <div>
        {% include '/navbar/navbar.html' %}
     </div>
    <div style="margin-top: 70px;">
        <!-- can be a carousel -->
        <div id="demo" class="carousel slide" data-bs-ride="carousel">
            <!-- Indicators/dots -->
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
              <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
            </div>
            <!-- The slideshow/carousel -->
            <!--  carousel logic can be changed. .... -->
            <div class="carousel-inner" style="height: 300px;">
              <div class="carousel-item active">
                <img src="/static/images/home_image.png" alt="Los Angeles" class="d-block" style="width:100%;">
              </div>
              <div class="carousel-item">
                <img src="/static/images/home_image.png" alt="Chicago" class="d-block" style="width:100%">
              </div>
            </div>
            
            <!-- Left and right controls/icons -->
            <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
              <span class="carousel-control-prev-icon"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
              <span class="carousel-control-next-icon"></span>
            </button>
          </div>
          
        <!-- display all the posts -->
         <div style="display: flex; flex-direction: row; flex-wrap: wrap; justify-content: space-between;">
          <!-- loop through & .... -->
          {% for key, blogs_list in blogs.items() %}
          {% for blog in blogs_list %}
          <div class="card" style="width: 15rem; margin: 10px;">
            <img class="card-img-top" src="{{blog[3]}}" alt="Card image cap">
            <div class="card-body">
              <span>By : {{blog[5]}} - {{blog[4]}}</span> <hr>
              <h5 class="card-title">{{blog[1]}}</h5>
              <p class="card-text" style="max-height: 100px; overflow: hidden;">{{blog[2]}}.</p>
              <a href="/blogs/{{blog[0]}}" class="btn btn-primary">Go to Details</a>
            </div>
          </div>
          {% endfor %}
          {% endfor %}
         </div>
    </div>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home_styles.css') }}">
    <title>{{title}}</title>
</head>
<body>
    <!-- Include navbar here from navbar.html -->
    {% include '/navbar/navbar.html' %}

    <!-- exmpore more blogs link -->
    <div id="explore_blogs_link">
        <a class="alert alert-success" href="/blogs" style="text-decoration: none; color: blueviolet;">Explore Blogs !</a>
    </div>
    <!-- Include js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/navbar/navbar.html
<!-- include / link css files -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/nav_styles.css') }}">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
          <p class="navbar-brand" style="color: white">{{brand_nav_text}}</p>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('views.index')}}">{{home_nav_text}}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/blogs">{{blogs_nav_text}}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="auth/login-page" tabindex="-1">{{admin_login_nav_text}}</a>
              </li>
            </ul>
            <!-- <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search Blogs" aria-label="Search">
              <button class="btn btn-outline-warning" type="submit" style="color: whitesmoke">{{search_nav_text}}</button>
            </form> -->
          </div>
    </div>
</nav>

    